
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Cipher
 */
public class cancellation extends javax.swing.JFrame {
    String name;
    int total;
    /**
     * Creates new form cancellation
     */
    public cancellation(String s,int i) {
        initComponents();
        name=s;
        total=i;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        p1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("BankGothic Lt BT", 0, 48)); // NOI18N
        jLabel3.setText("Cancellation Form");

        jLabel11.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel11.setText("Password:");

        jLabel12.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        jLabel12.setText("Booking Reference No.:");

        b2.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        b2.setText("ok");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("BankGothic Lt BT", 0, 24)); // NOI18N
        b1.setText("Back");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(124, 124, 124)
                                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(b1)
                                    .addGap(153, 153, 153)
                                    .addComponent(b2)
                                    .addGap(162, 162, 162))))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2)
                    .addComponent(b1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
String book_ref_no =  t1.getText();
String passwordd = new String(p1.getPassword());
String cin=null;


                                           
     
if (book_ref_no.isEmpty())
    JOptionPane.showMessageDialog(this,"Booking Ref No not entered");
else if (passwordd.isEmpty())
    JOptionPane.showMessageDialog(this,"Password is not entered");
else
{
    try
    {
        Class.forName("java.sql.DriverManager");
        Connection con = (Connection)

        DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_buddy","root","2358");
        Statement stmt =(Statement) con.createStatement();
        
        String query="SELECT * FROM prime_info WHERE book_ref_no='"+book_ref_no+"';";  
        ResultSet rs=stmt.executeQuery(query);    
    
     // String username=rs.getString("username");
      
      String username=null;
      String password=null;
                                                                        
        if (rs.next())
      {   
          username=rs.getString("username");
          cin=rs.getString("cin");
         
      }
         else    
         JOptionPane.showMessageDialog (this,"Sorry!Enter ccorrect Booking Ref No");  
        
                                                // JOptionPane.showMessageDialog (this,"cin mil gaya");  
        
                                                 
                                                 
                                                 
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
//String date="22-03-2016";
  //JOptionPane.showMessageDialog(this,sdf.parse(cin));
         
      /*  Statement stmt5 =(Statement) con.createStatement();  
        String query5="SELECT datediff("+sdf.parse(cin)+",curdate()) as diff";
        ResultSet rs5=stmt5.executeQuery(query5);
        rs5.next();
        String diff=rs5.getString("diff");
        
                                                JOptionPane.showMessageDialog (this,diff);  
        
            */                                    
        
        
        

       Statement stmt1 =(Statement) con.createStatement();  
        String query1="SELECT * FROM sign_up WHERE username='"+username+"';";  
        ResultSet rs1=stmt1.executeQuery(query1); 
        
        
        
        
         if (rs1.next())
      {   
          password =rs1.getString("password");
         
      }
         else    
         JOptionPane.showMessageDialog (this,"Sorry!Please try again");   
        
         
                                                                             //JOptionPane.showMessageDialog(this,passwordd);
         
          Statement stmt4 =(Statement) con.createStatement();  
        String query4="SELECT sha1('"+passwordd+"');";
        ResultSet rs4=stmt4.executeQuery(query4);                                                                    
        String append="sha1('"+passwordd+"')";
        
        rs4.next();
        passwordd=rs4.getString(append);
         
                                                                             
        
        
                                                                             
                                                                             
         if(password.equals(passwordd)){
             Statement stmt2 =(Statement) con.createStatement();
              String query2="Delete from Prime_info WHERE book_ref_no='"+book_ref_no+"';";  
             //rowsDeleted = statement.executeUpdate();
             int rowsDeleted = stmt2.executeUpdate(query2);
             
             //int dif=Integer.parseInt(diff);
                if (rowsDeleted > 0) {
                    /*if(dif>3){
                        JOptionPane.showMessageDialog(this,"Booking cancelled successfully");
                    }
                    else{
                        double deduc=0.5*total;
                        JOptionPane.showMessageDialog(this,deduc+" will be charged");
                        JOptionPane.showMessageDialog(this,"Booking cancelled successfully");
                    }*/
                    
                     JOptionPane.showMessageDialog(this,"Booking cancelled successfully");
                        
                    
                    
                    
                    
                }
                else{
                    t1.setText("");
                    p1.setText("");
                    
                    JOptionPane.showMessageDialog(this,"Please try again");
                     
                }
         }
          else
           JOptionPane.showMessageDialog(this,"Enter correct password");
             
             
            // ResultSet rs2=stmt.executeUpdate(query2); 
         }

    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

}




        
home_page obj1=new home_page(name);
obj1.setVisible(true);
this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
home_page obj=new home_page(name);
obj.setVisible(true);
this.dispose();



        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cancellation(null,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField p1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
